# Hexo Configuration
# Documentation: https://hexo.io/docs/configuration.html

# Site
title: Henry's Blog
subtitle: 莫道桑榆晚，为霞尚满天
description: Henry的个人博客，分享网络安全、Python编程、NBA篮球等技术与生活内容。
author: Henry Hu
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://hhookurbanb.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# Writing
new_post_name: :title.md
default_layout: post
auto_spacing: false
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Category & Tag
default_category: 生活日常
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: minimal

# Deployment
deploy:
  type: git
  repo: https://github.com/HHookUrbanB/Blog.github.io.git
  branch: main
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
