(function(){'use strict';const C=window.MovieCore, DATA=window.MOVIE_CATALOG;
if(!C||!DATA){document.getElementById('results-count').textContent='资料未成功载入，请刷新页面或打开全部索引。';return;}
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=C.parse(location.search);const pageSize=24;let timer;
$('film-count').textContent=DATA.summary.movies;$('show-count').textContent=DATA.summary.shows;$('enriched-count').textContent=DATA.summary.externally_enriched_movies;
function options(id,values,label,unknown){$(id).innerHTML='<option value="">'+label+'</option>'+values.map(([v,l])=>'<option value="'+esc(v)+'">'+esc(l)+'</option>').join('')+(unknown?'<option value="unknown">'+unknown+'</option>':'');}
function facets(){const rows=DATA.records.filter(x=>x.kind===(state.kind==='shows'?'show':'movie'));const unique=k=>[...new Set(rows.flatMap(x=>x[k]))].sort((a,b)=>a.localeCompare(b,'zh'));
options('genre',unique('genres').map(x=>[x,x]),'全部类型');options('country',unique('countries').map(x=>[x,x]),'全部地区','地区待补');options('decade',[...new Set(rows.filter(x=>x.year!==null).map(x=>Math.floor(x.year/10)*10))].sort((a,b)=>b-a).map(x=>[x,x+' 年代']),'全部年代','年份待补');
$('runtime-filter').hidden=state.kind==='shows';$('sort').querySelector('[value="runtime-asc"]').disabled=state.kind==='shows';if(state.kind==='shows'&&state.sort==='runtime-asc')state.sort='title';}
function sync(){facets();$('query').value=state.q;for(const k of ['genre','decade','country','runtime','verification','sort']){if(![...$(k).options].some(o=>o.value===state[k]))state[k]='';$(k).value=state[k];}document.querySelectorAll('[data-kind]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.kind===state.kind)));}
function updateUrl(push){const qs=C.serialize(state),url=location.pathname+(qs?'?'+qs:'')+location.hash;if(url!==location.pathname+location.search+location.hash)history[push?'pushState':'replaceState'](null,'',url);}
function badge(r){if(r.verification_status==='needs_identity_review')return '<span class="status-badge review">身份待核对</span>';if(r.verification_status==='has_external_sources')return '<span class="status-badge verified">已补来源</span>';return '';}
function card(r,i){const year=r.year??'年份待补',duration=r.kind==='movie'?(r.runtime_minutes!==null?r.runtime_minutes+' 分钟':'片长待补'):(r.episodes!==null?r.episodes+' 集':'集数待补'),director=r.directors.length?r.directors.join(' / '):(r.kind==='movie'?'导演待补':'剧集与综艺');return '<article class="movie-card"><a class="movie-card-link" href="'+esc(r.detail_path)+'" aria-label="'+esc(r.title+'，'+year)+'"><div class="card-top"><span class="film-number">'+String(i+1).padStart(3,'0')+'</span>'+badge(r)+'</div><div class="card-body"><p class="card-year">'+esc(year)+'<span> / '+esc(duration)+'</span></p><h2>'+esc(r.title)+'</h2><p class="card-alias">'+esc(r.aliases[0]||'')+'</p><p class="card-director">'+esc(director)+'</p></div><div class="card-bottom"><span>'+esc(r.genres.slice(0,3).join(' · ')||'类型待补')+'</span><span class="card-arrow" aria-hidden="true">↗</span></div></a></article>';}
function render(push=false){const result=C.sorted(C.filter(DATA.records,state),state.sort),pages=Math.max(1,Math.ceil(result.length/pageSize));state.page=Math.min(pages,state.page);updateUrl(push);$('clear-query').hidden=!state.q;$('results-count').innerHTML='<strong>'+result.length+'</strong> 条'+(state.kind==='shows'?'剧集与综艺':'电影')+(state.q?' · “'+esc(state.q)+'”':'');$('results').className='movie-grid '+(state.view==='list'?'list-view':'');$('results').innerHTML=result.slice((state.page-1)*pageSize,state.page*pageSize).map((r,i)=>card(r,i+(state.page-1)*pageSize)).join('');$('empty').hidden=result.length>0;$('grid-view').setAttribute('aria-pressed',state.view==='grid');$('list-view').setAttribute('aria-pressed',state.view==='list');
$('active-filters').innerHTML=['genre','decade','country','runtime','verification'].filter(k=>state[k]).map(k=>'<button type="button" data-remove="'+k+'" aria-label="移除筛选 '+esc($(k).selectedOptions[0].textContent)+'">'+esc($(k).selectedOptions[0].textContent)+' <span aria-hidden="true">×</span></button>').join('');
$('pagination').innerHTML=result.length?'<button type="button" data-page="'+(state.page-1)+'" '+(state.page===1?'disabled':'')+'>← 上一页</button><span>第 '+state.page+' / '+pages+' 页</span><button type="button" data-page="'+(state.page+1)+'" '+(state.page===pages?'disabled':'')+'>下一页 →</button>':'';
}
function changed(push=true){clearTimeout(timer);state.page=1;sync();render(push);}
$('query').addEventListener('input',()=>{clearTimeout(timer);state.q=$('query').value;state.page=1;timer=setTimeout(()=>render(false),140);});$('search-form').addEventListener('submit',e=>{e.preventDefault();state.q=$('query').value;changed();});$('clear-query').addEventListener('click',()=>{state.q='';changed();$('query').focus();});
for(const k of ['genre','decade','country','runtime','verification','sort'])$(k).addEventListener('change',()=>{state[k]=$(k).value;changed();});
document.querySelectorAll('[data-kind]').forEach(btn=>btn.addEventListener('click',()=>{state={...C.defaults,kind:btn.dataset.kind,q:state.q,view:state.view};changed();}));
document.querySelectorAll('[data-query]').forEach(btn=>btn.addEventListener('click',()=>{state={...C.defaults,q:btn.dataset.query};changed();$('query').focus();}));
const reset=()=>{state={...C.defaults,kind:state.kind,view:state.view};changed();};$('reset').addEventListener('click',reset);$('empty-reset').addEventListener('click',reset);
$('active-filters').addEventListener('click',e=>{const btn=e.target.closest('[data-remove]');if(btn){state[btn.dataset.remove]='';changed();}});
$('pagination').addEventListener('click',e=>{const btn=e.target.closest('[data-page]');if(btn&&!btn.disabled){state.page=Number(btn.dataset.page);render(true);$('catalog').scrollIntoView({behavior:'instant'});$('results-count').setAttribute('tabindex','-1');$('results-count').focus({preventScroll:true});}});
$('grid-view').addEventListener('click',()=>{state.view='grid';render(true);});$('list-view').addEventListener('click',()=>{state.view='list';render(true);});
window.addEventListener('popstate',()=>{clearTimeout(timer);state=C.parse(location.search);sync();render();});sync();render();
})();
